### PR TITLE
Bugfix and tests for RegularCartesianGrid

### PR DESCRIPTION
**Pull request by glwagner**
This fixes a minor bug in the grid constructor and contributes some simple tests to verify correct grid construction. It also adds the syntax

```julia
g = RegularCartesianGrid(Float32, (nx, ny, nz), (Lx, Ly, Lz))
```

for constructing grids with element type `Float32` (for example).

### CODE REVIEW

**Comment by glwagner** [comment]
Right --- the core functions cannot allocate memory. Even `@views` may not be best for the final code because it allocates some memory.

I would have written the `xderiv` functions, but I wasn't exactly sure how to deal with the staggered grid --- does the differentiation formula depend on whether the variable is stored at cell centers or cell faces?

**Comment by ali-ramadhan** [comment]
Yeah it'll be slow but I figure we can always optimize later...

The velocities stored are defined as averages over the cell faces (well the velocities are normal to the cell faces) while tracer variables (e.g. temperature T, salinity S, and pressure p) are defined as cell or volume averages. The difference is reflected in the different operators, e.g. [div_flux](https://github.com/ali-ramadhan/OceanLES.jl/blob/69d1b5794e297245289be993d254ec795469061a/src/operators.jl#L46) vs. [u_dot_u](https://github.com/ali-ramadhan/OceanLES.jl/blob/69d1b5794e297245289be993d254ec795469061a/src/operators.jl#L59), which I guess is why the δ operators aren't exactly derivatives as much as they are difference operators used by the actual divergence and curl operators.

**Comment by glwagner** [comment]
Well, that explains some of my flailing!

Ok, I agree with what you're saying. 

Should we anticipate that functions should mutate some output array, so function signatures will generally be something like `operation!(out, in, otherargs...)`?

Anticipating the basic code pattern will reduce work later, and it'll still be possible to write `operation!` quick and dirty.

**Comment by ali-ramadhan** [comment]
On that note, we have a lot of the algorithmic details written up in Overleaf so I can use it to bootstrap some documentation (as soon as the deep convection example works...).

And yeah I'm not sure yet which operations will look like `operation!(out, in, ...)` although probably all of them at the derivative operator level will as it's supposed to be as fast as possible.

**Comment by glwagner** [comment]
My experience is that essentially all non-constructor functions take this form.

Functions that output something will likely only be called during the construction of types --- which occurs once in the model lifecycle, during initialization. After model initialization, almost no new memory can be allocated; therefore all functions mutate existing data structures.

This concept manifests even at the user-level, where one scripting pattern might be

```
model = Model(parameters...)

set_ic!(model, ic)

run!(model)
```

In this case, the user obtains an output (`model`) from the `Model` constructor at model initialization. Subsequently, all compute-intensive operations act to mutate 'model' in place.

**Pull request merged**
